package com.youmai.hxsdk.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.youmai.hxsdk.db.bean.CacheMsgBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CACHE_MSG_BEAN".
*/
public class CacheMsgBeanDao extends AbstractDao<CacheMsgBean, Long> {

    public static final String TABLENAME = "CACHE_MSG_BEAN";

    /**
     * Properties of entity CacheMsgBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MsgId = new Property(1, Long.class, "msgId", false, "MSG_ID");
        public final static Property MsgType = new Property(2, int.class, "msgType", false, "MSG_TYPE");
        public final static Property MsgTime = new Property(3, long.class, "msgTime", false, "MSG_TIME");
        public final static Property SenderUserId = new Property(4, String.class, "senderUserId", false, "SENDER_USER_ID");
        public final static Property ReceiverUserId = new Property(5, String.class, "receiverUserId", false, "RECEIVER_USER_ID");
        public final static Property ContentJsonBody = new Property(6, String.class, "contentJsonBody", false, "CONTENT_JSON_BODY");
        public final static Property GroupId = new Property(7, int.class, "groupId", false, "GROUP_ID");
        public final static Property TargetUuid = new Property(8, String.class, "targetUuid", false, "TARGET_UUID");
        public final static Property MsgStatus = new Property(9, int.class, "msgStatus", false, "MSG_STATUS");
        public final static Property Progress = new Property(10, int.class, "progress", false, "PROGRESS");
    }


    public CacheMsgBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CacheMsgBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CACHE_MSG_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MSG_ID\" INTEGER," + // 1: msgId
                "\"MSG_TYPE\" INTEGER NOT NULL ," + // 2: msgType
                "\"MSG_TIME\" INTEGER NOT NULL ," + // 3: msgTime
                "\"SENDER_USER_ID\" TEXT," + // 4: senderUserId
                "\"RECEIVER_USER_ID\" TEXT," + // 5: receiverUserId
                "\"CONTENT_JSON_BODY\" TEXT," + // 6: contentJsonBody
                "\"GROUP_ID\" INTEGER NOT NULL ," + // 7: groupId
                "\"TARGET_UUID\" TEXT," + // 8: targetUuid
                "\"MSG_STATUS\" INTEGER NOT NULL ," + // 9: msgStatus
                "\"PROGRESS\" INTEGER NOT NULL );"); // 10: progress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CACHE_MSG_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CacheMsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindLong(2, msgId);
        }
        stmt.bindLong(3, entity.getMsgType());
        stmt.bindLong(4, entity.getMsgTime());
 
        String senderUserId = entity.getSenderUserId();
        if (senderUserId != null) {
            stmt.bindString(5, senderUserId);
        }
 
        String receiverUserId = entity.getReceiverUserId();
        if (receiverUserId != null) {
            stmt.bindString(6, receiverUserId);
        }
 
        String contentJsonBody = entity.getContentJsonBody();
        if (contentJsonBody != null) {
            stmt.bindString(7, contentJsonBody);
        }
        stmt.bindLong(8, entity.getGroupId());
 
        String targetUuid = entity.getTargetUuid();
        if (targetUuid != null) {
            stmt.bindString(9, targetUuid);
        }
        stmt.bindLong(10, entity.getMsgStatus());
        stmt.bindLong(11, entity.getProgress());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CacheMsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindLong(2, msgId);
        }
        stmt.bindLong(3, entity.getMsgType());
        stmt.bindLong(4, entity.getMsgTime());
 
        String senderUserId = entity.getSenderUserId();
        if (senderUserId != null) {
            stmt.bindString(5, senderUserId);
        }
 
        String receiverUserId = entity.getReceiverUserId();
        if (receiverUserId != null) {
            stmt.bindString(6, receiverUserId);
        }
 
        String contentJsonBody = entity.getContentJsonBody();
        if (contentJsonBody != null) {
            stmt.bindString(7, contentJsonBody);
        }
        stmt.bindLong(8, entity.getGroupId());
 
        String targetUuid = entity.getTargetUuid();
        if (targetUuid != null) {
            stmt.bindString(9, targetUuid);
        }
        stmt.bindLong(10, entity.getMsgStatus());
        stmt.bindLong(11, entity.getProgress());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CacheMsgBean readEntity(Cursor cursor, int offset) {
        CacheMsgBean entity = new CacheMsgBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // msgId
            cursor.getInt(offset + 2), // msgType
            cursor.getLong(offset + 3), // msgTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // senderUserId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // receiverUserId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // contentJsonBody
            cursor.getInt(offset + 7), // groupId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // targetUuid
            cursor.getInt(offset + 9), // msgStatus
            cursor.getInt(offset + 10) // progress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CacheMsgBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMsgId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMsgType(cursor.getInt(offset + 2));
        entity.setMsgTime(cursor.getLong(offset + 3));
        entity.setSenderUserId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setReceiverUserId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setContentJsonBody(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setGroupId(cursor.getInt(offset + 7));
        entity.setTargetUuid(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setMsgStatus(cursor.getInt(offset + 9));
        entity.setProgress(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CacheMsgBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CacheMsgBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CacheMsgBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
