package com.youmai.hxsdk.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.youmai.hxsdk.db.bean.CacheMsgBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CACHE_MSG_BEAN".
*/
public class CacheMsgBeanDao extends AbstractDao<CacheMsgBean, Long> {

    public static final String TABLENAME = "CACHE_MSG_BEAN";

    /**
     * Properties of entity CacheMsgBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MsgId = new Property(1, Long.class, "msgId", false, "MSG_ID");
        public final static Property MsgType = new Property(2, int.class, "msgType", false, "MSG_TYPE");
        public final static Property MsgStatus = new Property(3, int.class, "msgStatus", false, "MSG_STATUS");
        public final static Property MsgTime = new Property(4, long.class, "msgTime", false, "MSG_TIME");
        public final static Property SenderUserId = new Property(5, int.class, "senderUserId", false, "SENDER_USER_ID");
        public final static Property ReceiverUserId = new Property(6, int.class, "receiverUserId", false, "RECEIVER_USER_ID");
        public final static Property SenderPhone = new Property(7, String.class, "senderPhone", false, "SENDER_PHONE");
        public final static Property ReceiverPhone = new Property(8, String.class, "receiverPhone", false, "RECEIVER_PHONE");
        public final static Property TargetPhone = new Property(9, String.class, "targetPhone", false, "TARGET_PHONE");
        public final static Property ContentJsonBody = new Property(10, String.class, "contentJsonBody", false, "CONTENT_JSON_BODY");
        public final static Property Progress = new Property(11, int.class, "progress", false, "PROGRESS");
    }


    public CacheMsgBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CacheMsgBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CACHE_MSG_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MSG_ID\" INTEGER," + // 1: msgId
                "\"MSG_TYPE\" INTEGER NOT NULL ," + // 2: msgType
                "\"MSG_STATUS\" INTEGER NOT NULL ," + // 3: msgStatus
                "\"MSG_TIME\" INTEGER NOT NULL ," + // 4: msgTime
                "\"SENDER_USER_ID\" INTEGER NOT NULL ," + // 5: senderUserId
                "\"RECEIVER_USER_ID\" INTEGER NOT NULL ," + // 6: receiverUserId
                "\"SENDER_PHONE\" TEXT," + // 7: senderPhone
                "\"RECEIVER_PHONE\" TEXT," + // 8: receiverPhone
                "\"TARGET_PHONE\" TEXT," + // 9: targetPhone
                "\"CONTENT_JSON_BODY\" TEXT," + // 10: contentJsonBody
                "\"PROGRESS\" INTEGER NOT NULL );"); // 11: progress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CACHE_MSG_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CacheMsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindLong(2, msgId);
        }
        stmt.bindLong(3, entity.getMsgType());
        stmt.bindLong(4, entity.getMsgStatus());
        stmt.bindLong(5, entity.getMsgTime());
        stmt.bindLong(6, entity.getSenderUserId());
        stmt.bindLong(7, entity.getReceiverUserId());
 
        String senderPhone = entity.getSenderPhone();
        if (senderPhone != null) {
            stmt.bindString(8, senderPhone);
        }
 
        String receiverPhone = entity.getReceiverPhone();
        if (receiverPhone != null) {
            stmt.bindString(9, receiverPhone);
        }
 
        String targetPhone = entity.getTargetPhone();
        if (targetPhone != null) {
            stmt.bindString(10, targetPhone);
        }
 
        String contentJsonBody = entity.getContentJsonBody();
        if (contentJsonBody != null) {
            stmt.bindString(11, contentJsonBody);
        }
        stmt.bindLong(12, entity.getProgress());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CacheMsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindLong(2, msgId);
        }
        stmt.bindLong(3, entity.getMsgType());
        stmt.bindLong(4, entity.getMsgStatus());
        stmt.bindLong(5, entity.getMsgTime());
        stmt.bindLong(6, entity.getSenderUserId());
        stmt.bindLong(7, entity.getReceiverUserId());
 
        String senderPhone = entity.getSenderPhone();
        if (senderPhone != null) {
            stmt.bindString(8, senderPhone);
        }
 
        String receiverPhone = entity.getReceiverPhone();
        if (receiverPhone != null) {
            stmt.bindString(9, receiverPhone);
        }
 
        String targetPhone = entity.getTargetPhone();
        if (targetPhone != null) {
            stmt.bindString(10, targetPhone);
        }
 
        String contentJsonBody = entity.getContentJsonBody();
        if (contentJsonBody != null) {
            stmt.bindString(11, contentJsonBody);
        }
        stmt.bindLong(12, entity.getProgress());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CacheMsgBean readEntity(Cursor cursor, int offset) {
        CacheMsgBean entity = new CacheMsgBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // msgId
            cursor.getInt(offset + 2), // msgType
            cursor.getInt(offset + 3), // msgStatus
            cursor.getLong(offset + 4), // msgTime
            cursor.getInt(offset + 5), // senderUserId
            cursor.getInt(offset + 6), // receiverUserId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // senderPhone
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // receiverPhone
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // targetPhone
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // contentJsonBody
            cursor.getInt(offset + 11) // progress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CacheMsgBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMsgId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMsgType(cursor.getInt(offset + 2));
        entity.setMsgStatus(cursor.getInt(offset + 3));
        entity.setMsgTime(cursor.getLong(offset + 4));
        entity.setSenderUserId(cursor.getInt(offset + 5));
        entity.setReceiverUserId(cursor.getInt(offset + 6));
        entity.setSenderPhone(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setReceiverPhone(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTargetPhone(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setContentJsonBody(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setProgress(cursor.getInt(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CacheMsgBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CacheMsgBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CacheMsgBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
