package com.youmai.hxsdk.db.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 16): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 16;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        AppAuthCfgDao.createTable(db, ifNotExists);
        AppCfgDao.createTable(db, ifNotExists);
        BusinessCardDataDao.createTable(db, ifNotExists);
        BusinessCardInfoDao.createTable(db, ifNotExists);
        CacheMsgBeanDao.createTable(db, ifNotExists);
        CardDao.createTable(db, ifNotExists);
        ChatMsgDao.createTable(db, ifNotExists);
        ContCfgDao.createTable(db, ifNotExists);
        HxUsersDao.createTable(db, ifNotExists);
        ImCardModelDao.createTable(db, ifNotExists);
        OwnerDataDao.createTable(db, ifNotExists);
        PhoneCardsDao.createTable(db, ifNotExists);
        PushMsgDao.createTable(db, ifNotExists);
        RemindMsgDao.createTable(db, ifNotExists);
        ShowCfgDao.createTable(db, ifNotExists);
        ShowDataDao.createTable(db, ifNotExists);
        StatsCfgDao.createTable(db, ifNotExists);
        StatsDataDao.createTable(db, ifNotExists);
        UIDataDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        AppAuthCfgDao.dropTable(db, ifExists);
        AppCfgDao.dropTable(db, ifExists);
        BusinessCardDataDao.dropTable(db, ifExists);
        BusinessCardInfoDao.dropTable(db, ifExists);
        CacheMsgBeanDao.dropTable(db, ifExists);
        CardDao.dropTable(db, ifExists);
        ChatMsgDao.dropTable(db, ifExists);
        ContCfgDao.dropTable(db, ifExists);
        HxUsersDao.dropTable(db, ifExists);
        ImCardModelDao.dropTable(db, ifExists);
        OwnerDataDao.dropTable(db, ifExists);
        PhoneCardsDao.dropTable(db, ifExists);
        PushMsgDao.dropTable(db, ifExists);
        RemindMsgDao.dropTable(db, ifExists);
        ShowCfgDao.dropTable(db, ifExists);
        ShowDataDao.dropTable(db, ifExists);
        StatsCfgDao.dropTable(db, ifExists);
        StatsDataDao.dropTable(db, ifExists);
        UIDataDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AppAuthCfgDao.class);
        registerDaoClass(AppCfgDao.class);
        registerDaoClass(BusinessCardDataDao.class);
        registerDaoClass(BusinessCardInfoDao.class);
        registerDaoClass(CacheMsgBeanDao.class);
        registerDaoClass(CardDao.class);
        registerDaoClass(ChatMsgDao.class);
        registerDaoClass(ContCfgDao.class);
        registerDaoClass(HxUsersDao.class);
        registerDaoClass(ImCardModelDao.class);
        registerDaoClass(OwnerDataDao.class);
        registerDaoClass(PhoneCardsDao.class);
        registerDaoClass(PushMsgDao.class);
        registerDaoClass(RemindMsgDao.class);
        registerDaoClass(ShowCfgDao.class);
        registerDaoClass(ShowDataDao.class);
        registerDaoClass(StatsCfgDao.class);
        registerDaoClass(StatsDataDao.class);
        registerDaoClass(UIDataDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
