package com.youmai.hxsdk.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.youmai.hxsdk.db.bean.CacheMsgBean;
import com.youmai.hxsdk.db.bean.EmployeeBean;
import com.youmai.hxsdk.db.bean.GroupInfoBean;
import com.youmai.hxsdk.db.bean.ContactBean;

import com.youmai.hxsdk.db.dao.CacheMsgBeanDao;
import com.youmai.hxsdk.db.dao.EmployeeBeanDao;
import com.youmai.hxsdk.db.dao.GroupInfoBeanDao;
import com.youmai.hxsdk.db.dao.ContactBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheMsgBeanDaoConfig;
    private final DaoConfig employeeBeanDaoConfig;
    private final DaoConfig groupInfoBeanDaoConfig;
    private final DaoConfig contactBeanDaoConfig;

    private final CacheMsgBeanDao cacheMsgBeanDao;
    private final EmployeeBeanDao employeeBeanDao;
    private final GroupInfoBeanDao groupInfoBeanDao;
    private final ContactBeanDao contactBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheMsgBeanDaoConfig = daoConfigMap.get(CacheMsgBeanDao.class).clone();
        cacheMsgBeanDaoConfig.initIdentityScope(type);

        employeeBeanDaoConfig = daoConfigMap.get(EmployeeBeanDao.class).clone();
        employeeBeanDaoConfig.initIdentityScope(type);

        groupInfoBeanDaoConfig = daoConfigMap.get(GroupInfoBeanDao.class).clone();
        groupInfoBeanDaoConfig.initIdentityScope(type);

        contactBeanDaoConfig = daoConfigMap.get(ContactBeanDao.class).clone();
        contactBeanDaoConfig.initIdentityScope(type);

        cacheMsgBeanDao = new CacheMsgBeanDao(cacheMsgBeanDaoConfig, this);
        employeeBeanDao = new EmployeeBeanDao(employeeBeanDaoConfig, this);
        groupInfoBeanDao = new GroupInfoBeanDao(groupInfoBeanDaoConfig, this);
        contactBeanDao = new ContactBeanDao(contactBeanDaoConfig, this);

        registerDao(CacheMsgBean.class, cacheMsgBeanDao);
        registerDao(EmployeeBean.class, employeeBeanDao);
        registerDao(GroupInfoBean.class, groupInfoBeanDao);
        registerDao(ContactBean.class, contactBeanDao);
    }
    
    public void clear() {
        cacheMsgBeanDaoConfig.clearIdentityScope();
        employeeBeanDaoConfig.clearIdentityScope();
        groupInfoBeanDaoConfig.clearIdentityScope();
        contactBeanDaoConfig.clearIdentityScope();
    }

    public CacheMsgBeanDao getCacheMsgBeanDao() {
        return cacheMsgBeanDao;
    }

    public EmployeeBeanDao getEmployeeBeanDao() {
        return employeeBeanDao;
    }

    public GroupInfoBeanDao getGroupInfoBeanDao() {
        return groupInfoBeanDao;
    }

    public ContactBeanDao getContactBeanDao() {
        return contactBeanDao;
    }

}
