package com.youmai.hxsdk.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.youmai.hxsdk.db.bean.CacheMsgBean;
import com.youmai.hxsdk.db.bean.Contact;
import com.youmai.hxsdk.db.bean.EmployeeBean;
import com.youmai.hxsdk.db.bean.GroupInfoBean;

import com.youmai.hxsdk.db.dao.CacheMsgBeanDao;
import com.youmai.hxsdk.db.dao.ContactDao;
import com.youmai.hxsdk.db.dao.EmployeeBeanDao;
import com.youmai.hxsdk.db.dao.GroupInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheMsgBeanDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig employeeBeanDaoConfig;
    private final DaoConfig groupInfoBeanDaoConfig;

    private final CacheMsgBeanDao cacheMsgBeanDao;
    private final ContactDao contactDao;
    private final EmployeeBeanDao employeeBeanDao;
    private final GroupInfoBeanDao groupInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheMsgBeanDaoConfig = daoConfigMap.get(CacheMsgBeanDao.class).clone();
        cacheMsgBeanDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        employeeBeanDaoConfig = daoConfigMap.get(EmployeeBeanDao.class).clone();
        employeeBeanDaoConfig.initIdentityScope(type);

        groupInfoBeanDaoConfig = daoConfigMap.get(GroupInfoBeanDao.class).clone();
        groupInfoBeanDaoConfig.initIdentityScope(type);

        cacheMsgBeanDao = new CacheMsgBeanDao(cacheMsgBeanDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        employeeBeanDao = new EmployeeBeanDao(employeeBeanDaoConfig, this);
        groupInfoBeanDao = new GroupInfoBeanDao(groupInfoBeanDaoConfig, this);

        registerDao(CacheMsgBean.class, cacheMsgBeanDao);
        registerDao(Contact.class, contactDao);
        registerDao(EmployeeBean.class, employeeBeanDao);
        registerDao(GroupInfoBean.class, groupInfoBeanDao);
    }
    
    public void clear() {
        cacheMsgBeanDaoConfig.clearIdentityScope();
        contactDaoConfig.clearIdentityScope();
        employeeBeanDaoConfig.clearIdentityScope();
        groupInfoBeanDaoConfig.clearIdentityScope();
    }

    public CacheMsgBeanDao getCacheMsgBeanDao() {
        return cacheMsgBeanDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public EmployeeBeanDao getEmployeeBeanDao() {
        return employeeBeanDao;
    }

    public GroupInfoBeanDao getGroupInfoBeanDao() {
        return groupInfoBeanDao;
    }

}
