package com.youmai.hxsdk.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.youmai.hxsdk.db.bean.StatsCfg;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STATS_CFG".
*/
public class StatsCfgDao extends AbstractDao<StatsCfg, Long> {

    public static final String TABLENAME = "STATS_CFG";

    /**
     * Properties of entity StatsCfg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Table_id = new Property(0, Long.class, "table_id", true, "_id");
        public final static Property Id = new Property(1, int.class, "id", false, "ID");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
        public final static Property Weight = new Property(3, int.class, "weight", false, "WEIGHT");
    }


    public StatsCfgDao(DaoConfig config) {
        super(config);
    }
    
    public StatsCfgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STATS_CFG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: table_id
                "\"ID\" INTEGER NOT NULL ," + // 1: id
                "\"URL\" TEXT," + // 2: url
                "\"WEIGHT\" INTEGER NOT NULL );"); // 3: weight
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STATS_CFG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StatsCfg entity) {
        stmt.clearBindings();
 
        Long table_id = entity.getTable_id();
        if (table_id != null) {
            stmt.bindLong(1, table_id);
        }
        stmt.bindLong(2, entity.getId());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
        stmt.bindLong(4, entity.getWeight());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StatsCfg entity) {
        stmt.clearBindings();
 
        Long table_id = entity.getTable_id();
        if (table_id != null) {
            stmt.bindLong(1, table_id);
        }
        stmt.bindLong(2, entity.getId());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
        stmt.bindLong(4, entity.getWeight());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StatsCfg readEntity(Cursor cursor, int offset) {
        StatsCfg entity = new StatsCfg( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // table_id
            cursor.getInt(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // url
            cursor.getInt(offset + 3) // weight
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StatsCfg entity, int offset) {
        entity.setTable_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.getInt(offset + 1));
        entity.setUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWeight(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StatsCfg entity, long rowId) {
        entity.setTable_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StatsCfg entity) {
        if(entity != null) {
            return entity.getTable_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StatsCfg entity) {
        return entity.getTable_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
